main/urls.py
from django.urls import path
from .import views

#namespacing
app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    # path is default or empty
    # views is the file from which we call the index function (used here 
    # views.index, name="index") which we previously defined
    # we provide a name to this path called index, the
    # benefit of naming will be later made clear.
]

menu/urls.py
from django.urls import path
from .import views

#namespacing
app_name = "menu"

urlpatterns = [
    path('', views.index, name="index"),
    # path is default or empty
    # views is the file from which we call the index function
    # which we previously defined
    # we provide a name to this path called index, the
    # benefit of naming will be later made clear
]

pizzamama_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # the below url was already there when creating the superuser feature
    path('admin/', admin.site.urls), 
    # we create the url for the menu path and with the include method (default method)
    # by importing, we link the urls file as a string. menu = app name, urls = file name
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')), # this is for the mainpage, app added to the project
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):  
        return self.name 
        # display the name of the Pizzas

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    # return HttpResponse('The Main page')
    return render(request,'main/index.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza

# Create your views here.

# /menu : we have to explain to django that for the url of
# /menu it has to use the index function defined below,
# which sends a request to get an HttpResponse as a string
def index(request):
    '''
    pizzas = Pizza.objects.all() # gets all objects of Pizza
    pizza_names_and_price = [pizza.name + " : " + str(pizza.price)  + "$" for pizza in pizzas] # get only the names of pizzas
    pizza_names_and_price_str = ", ".join(pizza_names_and_price) # join the pizza names separated by comma
    return HttpResponse("Our pizzas - - - - - - : "+ pizza_names_and_price_str) # return pizza names from db
    '''
    pizzas = Pizza.objects.all().order_by('price') 
    # gets all objects of Pizza ordered by the values in the field price
    return render(request,'menu/index.html',{'pizzas':pizzas})

def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('price') # gets all pizza objects
    json = serializers.serialize("json", pizzas) # converts objects to json format
    return HttpResponse(json) # returns json object as a HttpResponse

main/templates/main/index.html
{% load static %}
<html lang="en">
        <head>
            <meta charset="UTF-8">
            <title> Pizza Mama </title>
            <link rel = "stylesheet" href="{% static 'main/style.css' %}">
        </head>
        <body>
        <div class="centered">
            <img id="small_logo" src = "{% static 'main/images/main_logo.png' %}" />
            <a href="{% url 'menu:index' %}">See our menu</a>
        </div>
        </body>        
    </html>

menu/templates/menu/index.html
{% load static %}
<html lang="en">
        <head>
            <meta charset="UTF-8">
            <title> Our Pizzas </title>
            <link rel = "stylesheet" href="{% static 'menu/style.css' %}">
        </head>
        <body>
        <a href="{% url 'main:index' %}"><img id="small_logo" src = "{% static 'menu/images/small_logo.png' %}" /></a>
        <div class="menu_title">
            <h1>Our Pizzas</h1>
        </div>
            
        <div class="menu_list">
            {% for pizza in pizzas %}
                <div class="menu_list_item">
                    <span class="menu_list_title">{{pizza.name}}</span>
                    <span class="menu_list_price">{{pizza.price | floatformat:2}}$</span>
                    <span class="menu_list_ingredients">{{pizza.ingredients}}</span>
                    {% if pizza.vegetarian %}
                    <span class="menu_list_badge">VEGETARIAN</span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        </body>        
    </html>